// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: takion.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Ps4RemotePlay.Protocol.Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TakionMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public PayloadType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BigPayload bigPayload { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BangPayload bangPayload { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public InfoPayload infoPayload { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public PacketLossPayload lossPayload { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public CorruptFramePayload corruptPayload { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public CursorPayload cursorPayload { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public TimerPayload timerPayload { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public DisconnectPayload disconnectPayload { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public LogPayload logPayload { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public HeaderRequestPayload headerPayload { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public DebugOption debugPayload { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public SenkushaPayload senkushaPayload { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public StreamInfoPayload streamInfoPayload { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public XmbCommandPayload xmbCommandPayload { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public ConnectionQualityPayload connectionQualityPayload { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public ClientMetricPayload clientMetricPayload { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public PlayTimeLeftPayload playTimeLeftPayload { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public ServerMessagePayload serverMessagePayload { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public FpsChangePayload fpsChangePayload { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public ControllerConnectionPayload controllerConnectionPayload { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public ClientInfoPayload clientInfoPayload { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public VideoCapturePayload videoCapturePayload { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public AudioCapturePayload audioCapturePayload { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public GkTracePayload gkTracePayload { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public PeriodicTimestampPayload periodicTimestampPayload { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public ServerSettingsPayload serverSettingsPayload { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public DirectMessagePayload directMessagePayload { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum PayloadType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BIG")]
            Big = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BANG")]
            Bang = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INFO")]
            Info = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"HEARTBEAT")]
            Heartbeat = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PACKETLOSS")]
            Packetloss = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CORRUPTFRAME")]
            Corruptframe = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"CURSOR")]
            Cursor = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"TIMER")]
            Timer = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"DISCONNECT")]
            Disconnect = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"LOG")]
            Log = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"HEADERREQUEST")]
            Headerrequest = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"DEBUG")]
            Debug = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"SENKUSHA")]
            Senkusha = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"STREAMINFO")]
            Streaminfo = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"STREAMINFOACK")]
            Streaminfoack = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"XMBCOMMAND")]
            Xmbcommand = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"CONNECTIONQUALITY")]
            Connectionquality = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENTMETRIC")]
            Clientmetric = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"PLAYTIMELEFT")]
            Playtimeleft = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"SERVERMESSAGE")]
            Servermessage = 19,
            [global::ProtoBuf.ProtoEnum(Name = @"FPSCHANGE")]
            Fpschange = 20,
            [global::ProtoBuf.ProtoEnum(Name = @"CONTROLLERCONNECTION")]
            Controllerconnection = 21,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENTINFO")]
            Clientinfo = 22,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEOCAPTURE")]
            Videocapture = 23,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIOCAPTURE")]
            Audiocapture = 24,
            [global::ProtoBuf.ProtoEnum(Name = @"IDRREQUEST")]
            Idrrequest = 25,
            [global::ProtoBuf.ProtoEnum(Name = @"GKTRACE")]
            Gktrace = 26,
            [global::ProtoBuf.ProtoEnum(Name = @"PERIODICTIMESTAMP")]
            Periodictimestamp = 27,
            [global::ProtoBuf.ProtoEnum(Name = @"SERVERSETTINGS")]
            Serversettings = 28,
            [global::ProtoBuf.ProtoEnum(Name = @"DIRECTMESSAGE")]
            Directmessage = 29,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventCode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string eventCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private string __pbn__Description;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BigPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint clientVersion { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string sessionKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string launchSpec { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public byte[] encryptedKey { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] ecdhPubKey
        {
            get { return __pbn__ecdhPubKey; }
            set { __pbn__ecdhPubKey = value; }
        }
        public bool ShouldSerializeecdhPubKey() => __pbn__ecdhPubKey != null;
        public void ResetecdhPubKey() => __pbn__ecdhPubKey = null;
        private byte[] __pbn__ecdhPubKey;

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] ecdhSig
        {
            get { return __pbn__ecdhSig; }
            set { __pbn__ecdhSig = value; }
        }
        public bool ShouldSerializeecdhSig() => __pbn__ecdhSig != null;
        public void ResetecdhSig() => __pbn__ecdhSig = null;
        private byte[] __pbn__ecdhSig;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BangPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint serverVersion { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"token", IsRequired = true)]
        public uint Token { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public bool encryptedKeyAccepted { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public bool versionAccepted { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string sessionKey { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public EventCode extendedInfo { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serverVersionString
        {
            get { return __pbn__serverVersionString ?? ""; }
            set { __pbn__serverVersionString = value; }
        }
        public bool ShouldSerializeserverVersionString() => __pbn__serverVersionString != null;
        public void ResetserverVersionString() => __pbn__serverVersionString = null;
        private string __pbn__serverVersionString;

        [global::ProtoBuf.ProtoMember(8)]
        public byte[] ecdhPubKey
        {
            get { return __pbn__ecdhPubKey; }
            set { __pbn__ecdhPubKey = value; }
        }
        public bool ShouldSerializeecdhPubKey() => __pbn__ecdhPubKey != null;
        public void ResetecdhPubKey() => __pbn__ecdhPubKey = null;
        private byte[] __pbn__ecdhPubKey;

        [global::ProtoBuf.ProtoMember(9)]
        public byte[] ecdhSig
        {
            get { return __pbn__ecdhSig; }
            set { __pbn__ecdhSig = value; }
        }
        public bool ShouldSerializeecdhSig() => __pbn__ecdhSig != null;
        public void ResetecdhSig() => __pbn__ecdhSig = null;
        private byte[] __pbn__ecdhSig;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InfoPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint effectiveBw { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"bitrate", IsRequired = true)]
        public uint Bitrate { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint minBitrate { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint targetBitrate { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint corruptFrameFreq { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"mtu", IsRequired = true)]
        public uint Mtu { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fps", IsRequired = true)]
        public uint Fps { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public uint monitorInterval { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public uint extOverhead { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public uint intOverhead { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public uint timeoutInterval { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public uint minResumeQuality { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public uint minFps { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CursorPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"width", IsRequired = true)]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"height", IsRequired = true)]
        public uint Height { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint hotspotX { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint hotspotY { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"pixels")]
        public byte[] Pixels
        {
            get { return __pbn__Pixels; }
            set { __pbn__Pixels = value; }
        }
        public bool ShouldSerializePixels() => __pbn__Pixels != null;
        public void ResetPixels() => __pbn__Pixels = null;
        private byte[] __pbn__Pixels;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimerPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint secondsLeft { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint totalSeconds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CorruptFramePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start", IsRequired = true)]
        public uint Start { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end", IsRequired = true)]
        public uint End { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PacketLossPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start", IsRequired = true)]
        public uint Start { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end", IsRequired = true)]
        public uint End { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint packetsReceived { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FpsChangePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fps", IsRequired = true)]
        public uint Fps { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisconnectPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason", IsRequired = true)]
        public string Reason { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public EventCode extendedInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level", IsRequired = true)]
        public LogLevel Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"component", IsRequired = true)]
        public string Component { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"timestampdouble")]
        public double Timestampdouble
        {
            get { return __pbn__Timestampdouble.GetValueOrDefault(); }
            set { __pbn__Timestampdouble = value; }
        }
        public bool ShouldSerializeTimestampdouble() => __pbn__Timestampdouble != null;
        public void ResetTimestampdouble() => __pbn__Timestampdouble = null;
        private double? __pbn__Timestampdouble;

        [global::ProtoBuf.ProtoContract()]
        public enum LogLevel
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CRITICAL")]
            Critical = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
            Error = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"WARNING")]
            Warning = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"INFO")]
            Info = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"DEBUG")]
            Debug = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TRACE")]
            Trace = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<LogMessage> Messages { get; } = new global::System.Collections.Generic.List<LogMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientMetric : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Category category { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int startFrame { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int endFrame { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"count", IsRequired = true)]
        public int Count { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"average", IsRequired = true)]
        public float Average { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public float stdDev { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public float minVal { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public float maxVal { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Category
        {
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_FRAMELIFETIME")]
            VideoFramelifetime = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_FRAMENALUSCOMPLETE")]
            VideoFramenaluscomplete = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_FECCORRECTION")]
            VideoFeccorrection = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_FRAMEQUEUE")]
            VideoFramequeue = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_DECODERFRAMEQUEUE")]
            VideoDecoderframequeue = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_SUBMITTODECODER")]
            VideoSubmittodecoder = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_DECODE")]
            VideoDecode = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_DECODEDPICTUREDROP")]
            VideoDecodedpicturedrop = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_YUVCOPY")]
            VideoYuvcopy = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_TEXTURECOPY")]
            VideoTexturecopy = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_RENDER")]
            VideoRender = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPHICS_PRERENDER")]
            GraphicsPrerender = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPHICS_PRESENT")]
            GraphicsPresent = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_FRAMELIFETIME")]
            AudioFramelifetime = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_FRAMENALUSCOMPLETE")]
            AudioFramenaluscomplete = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_FECCORRECTION")]
            AudioFeccorrection = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_FRAMEQUEUE")]
            AudioFramequeue = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_SUBMITTODECODER")]
            AudioSubmittodecoder = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_DECODE")]
            AudioDecode = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_BUFFERCOPY")]
            AudioBuffercopy = 19,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_RENDER")]
            AudioRender = 20,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientMetricPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<ClientMetric> Messages { get; } = new global::System.Collections.Generic.List<ClientMetric>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeaderRequestPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public HeaderType Type { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum HeaderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO")]
            Audio = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO")]
            Video = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugOption : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"overlay")]
        public OverlayPayload Overlay { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"bitrate")]
        public BitratePayload Bitrate { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OVERLAY")]
            Overlay = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BITRATE")]
            Bitrate = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OverlayPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enable")]
        public bool Enable
        {
            get { return __pbn__Enable.GetValueOrDefault(); }
            set { __pbn__Enable = value; }
        }
        public bool ShouldSerializeEnable() => __pbn__Enable != null;
        public void ResetEnable() => __pbn__Enable = null;
        private bool? __pbn__Enable;

        [global::ProtoBuf.ProtoMember(2, Name = @"toggle")]
        public bool Toggle
        {
            get { return __pbn__Toggle.GetValueOrDefault(); }
            set { __pbn__Toggle = value; }
        }
        public bool ShouldSerializeToggle() => __pbn__Toggle != null;
        public void ResetToggle() => __pbn__Toggle = null;
        private bool? __pbn__Toggle;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        [global::System.ComponentModel.DefaultValue(LogLocation.TopLeft)]
        public LogLocation Location
        {
            get { return __pbn__Location ?? LogLocation.TopLeft; }
            set { __pbn__Location = value; }
        }
        public bool ShouldSerializeLocation() => __pbn__Location != null;
        public void ResetLocation() => __pbn__Location = null;
        private LogLocation? __pbn__Location;

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public uint Level
        {
            get { return __pbn__Level.GetValueOrDefault(); }
            set { __pbn__Level = value; }
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoContract()]
        public enum LogLocation
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TOP_LEFT")]
            TopLeft = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TOP_RIGHT")]
            TopRight = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BOTTOM_LEFT")]
            BottomLeft = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"BOTTOM_RIGHT")]
            BottomRight = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BitratePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toggle")]
        public bool Toggle
        {
            get { return __pbn__Toggle.GetValueOrDefault(); }
            set { __pbn__Toggle = value; }
        }
        public bool ShouldSerializeToggle() => __pbn__Toggle != null;
        public void ResetToggle() => __pbn__Toggle = null;
        private bool? __pbn__Toggle;

        [global::ProtoBuf.ProtoMember(2)]
        public float bitrateChange
        {
            get { return __pbn__bitrateChange.GetValueOrDefault(); }
            set { __pbn__bitrateChange = value; }
        }
        public bool ShouldSerializebitrateChange() => __pbn__bitrateChange != null;
        public void ResetbitrateChange() => __pbn__bitrateChange = null;
        private float? __pbn__bitrateChange;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResolutionPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"width", IsRequired = true)]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"height", IsRequired = true)]
        public uint Height { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public byte[] videoHeader { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamInfoPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resolution")]
        public global::System.Collections.Generic.List<ResolutionPayload> Resolutions { get; } = new global::System.Collections.Generic.List<ResolutionPayload>();

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] audioHeader { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint startTimeout
        {
            get { return __pbn__startTimeout.GetValueOrDefault(); }
            set { __pbn__startTimeout = value; }
        }
        public bool ShouldSerializestartTimeout() => __pbn__startTimeout != null;
        public void ResetstartTimeout() => __pbn__startTimeout = null;
        private uint? __pbn__startTimeout;

        [global::ProtoBuf.ProtoMember(4)]
        public uint afkTimeout
        {
            get { return __pbn__afkTimeout.GetValueOrDefault(); }
            set { __pbn__afkTimeout = value; }
        }
        public bool ShouldSerializeafkTimeout() => __pbn__afkTimeout != null;
        public void ResetafkTimeout() => __pbn__afkTimeout = null;
        private uint? __pbn__afkTimeout;

        [global::ProtoBuf.ProtoMember(5)]
        public uint afkTimeoutDisconnect
        {
            get { return __pbn__afkTimeoutDisconnect.GetValueOrDefault(); }
            set { __pbn__afkTimeoutDisconnect = value; }
        }
        public bool ShouldSerializeafkTimeoutDisconnect() => __pbn__afkTimeoutDisconnect != null;
        public void ResetafkTimeoutDisconnect() => __pbn__afkTimeoutDisconnect = null;
        private uint? __pbn__afkTimeoutDisconnect;

        [global::ProtoBuf.ProtoMember(6)]
        public uint congestionControlInterval
        {
            get { return __pbn__congestionControlInterval.GetValueOrDefault(); }
            set { __pbn__congestionControlInterval = value; }
        }
        public bool ShouldSerializecongestionControlInterval() => __pbn__congestionControlInterval != null;
        public void ResetcongestionControlInterval() => __pbn__congestionControlInterval = null;
        private uint? __pbn__congestionControlInterval;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class XmbCommandPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"command", IsRequired = true)]
        public XmbCommand Command { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint playerId
        {
            get { return __pbn__playerId.GetValueOrDefault(); }
            set { __pbn__playerId = value; }
        }
        public bool ShouldSerializeplayerId() => __pbn__playerId != null;
        public void ResetplayerId() => __pbn__playerId = null;
        private uint? __pbn__playerId;

        [global::ProtoBuf.ProtoContract()]
        public enum XmbCommand
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OFF")]
            Off = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ON")]
            On = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TOGGLE")]
            Toggle = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectionQualityPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint targetBitrate
        {
            get { return __pbn__targetBitrate.GetValueOrDefault(); }
            set { __pbn__targetBitrate = value; }
        }
        public bool ShouldSerializetargetBitrate() => __pbn__targetBitrate != null;
        public void ResettargetBitrate() => __pbn__targetBitrate = null;
        private uint? __pbn__targetBitrate;

        [global::ProtoBuf.ProtoMember(2)]
        public uint upstreamBitrate
        {
            get { return __pbn__upstreamBitrate.GetValueOrDefault(); }
            set { __pbn__upstreamBitrate = value; }
        }
        public bool ShouldSerializeupstreamBitrate() => __pbn__upstreamBitrate != null;
        public void ResetupstreamBitrate() => __pbn__upstreamBitrate = null;
        private uint? __pbn__upstreamBitrate;

        [global::ProtoBuf.ProtoMember(3)]
        public float upstreamLoss
        {
            get { return __pbn__upstreamLoss.GetValueOrDefault(); }
            set { __pbn__upstreamLoss = value; }
        }
        public bool ShouldSerializeupstreamLoss() => __pbn__upstreamLoss != null;
        public void ResetupstreamLoss() => __pbn__upstreamLoss = null;
        private float? __pbn__upstreamLoss;

        [global::ProtoBuf.ProtoMember(4)]
        public bool disableUpstreamAudio
        {
            get { return __pbn__disableUpstreamAudio.GetValueOrDefault(); }
            set { __pbn__disableUpstreamAudio = value; }
        }
        public bool ShouldSerializedisableUpstreamAudio() => __pbn__disableUpstreamAudio != null;
        public void ResetdisableUpstreamAudio() => __pbn__disableUpstreamAudio = null;
        private bool? __pbn__disableUpstreamAudio;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayTimeLeftPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timeleft")]
        public uint Timeleft
        {
            get { return __pbn__Timeleft.GetValueOrDefault(); }
            set { __pbn__Timeleft = value; }
        }
        public bool ShouldSerializeTimeleft() => __pbn__Timeleft != null;
        public void ResetTimeleft() => __pbn__Timeleft = null;
        private uint? __pbn__Timeleft;

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerMessagePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"payload")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Payload
        {
            get { return __pbn__Payload ?? ""; }
            set { __pbn__Payload = value; }
        }
        public bool ShouldSerializePayload() => __pbn__Payload != null;
        public void ResetPayload() => __pbn__Payload = null;
        private string __pbn__Payload;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerConnectionPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int controllerId
        {
            get { return __pbn__controllerId.GetValueOrDefault(); }
            set { __pbn__controllerId = value; }
        }
        public bool ShouldSerializecontrollerId() => __pbn__controllerId != null;
        public void ResetcontrollerId() => __pbn__controllerId = null;
        private int? __pbn__controllerId;

        [global::ProtoBuf.ProtoMember(2, Name = @"connected")]
        public bool Connected
        {
            get { return __pbn__Connected.GetValueOrDefault(); }
            set { __pbn__Connected = value; }
        }
        public bool ShouldSerializeConnected() => __pbn__Connected != null;
        public void ResetConnected() => __pbn__Connected = null;
        private bool? __pbn__Connected;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(ControllerType.Notset)]
        public ControllerType controllerType
        {
            get { return __pbn__controllerType ?? ControllerType.Notset; }
            set { __pbn__controllerType = value; }
        }
        public bool ShouldSerializecontrollerType() => __pbn__controllerType != null;
        public void ResetcontrollerType() => __pbn__controllerType = null;
        private ControllerType? __pbn__controllerType;

        [global::ProtoBuf.ProtoContract()]
        public enum ControllerType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NOTSET")]
            Notset = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DUALSHOCK3")]
            Dualshock3 = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"DUALSHOCK4")]
            Dualshock4 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"VITA")]
            Vita = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"XINPUT")]
            Xinput = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientInfoPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string sessionKey { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint gcmTag
        {
            get { return __pbn__gcmTag.GetValueOrDefault(); }
            set { __pbn__gcmTag = value; }
        }
        public bool ShouldSerializegcmTag() => __pbn__gcmTag != null;
        public void ResetgcmTag() => __pbn__gcmTag = null;
        private uint? __pbn__gcmTag;

        [global::ProtoBuf.ProtoMember(3)]
        public uint keyPos
        {
            get { return __pbn__keyPos.GetValueOrDefault(); }
            set { __pbn__keyPos = value; }
        }
        public bool ShouldSerializekeyPos() => __pbn__keyPos != null;
        public void ResetkeyPos() => __pbn__keyPos = null;
        private uint? __pbn__keyPos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VideoCapturePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool serverSide
        {
            get { return __pbn__serverSide ?? false; }
            set { __pbn__serverSide = value; }
        }
        public bool ShouldSerializeserverSide() => __pbn__serverSide != null;
        public void ResetserverSide() => __pbn__serverSide = null;
        private bool? __pbn__serverSide;

        [global::ProtoBuf.ProtoMember(2, Name = @"idrperiod")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint Idrperiod
        {
            get { return __pbn__Idrperiod ?? 0; }
            set { __pbn__Idrperiod = value; }
        }
        public bool ShouldSerializeIdrperiod() => __pbn__Idrperiod != null;
        public void ResetIdrperiod() => __pbn__Idrperiod = null;
        private uint? __pbn__Idrperiod;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AudioCapturePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool serverSide
        {
            get { return __pbn__serverSide ?? false; }
            set { __pbn__serverSide = value; }
        }
        public bool ShouldSerializeserverSide() => __pbn__serverSide != null;
        public void ResetserverSide() => __pbn__serverSide = null;
        private bool? __pbn__serverSide;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerSettingsPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"idrperiod")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint Idrperiod
        {
            get { return __pbn__Idrperiod ?? 0; }
            set { __pbn__Idrperiod = value; }
        }
        public bool ShouldSerializeIdrperiod() => __pbn__Idrperiod != null;
        public void ResetIdrperiod() => __pbn__Idrperiod = null;
        private uint? __pbn__Idrperiod;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool sendPeriodicTimestamp
        {
            get { return __pbn__sendPeriodicTimestamp ?? false; }
            set { __pbn__sendPeriodicTimestamp = value; }
        }
        public bool ShouldSerializesendPeriodicTimestamp() => __pbn__sendPeriodicTimestamp != null;
        public void ResetsendPeriodicTimestamp() => __pbn__sendPeriodicTimestamp = null;
        private bool? __pbn__sendPeriodicTimestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GkTracePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint seqNo { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint gcmTag { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint keyPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeriodicTimestampPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public byte[] periodicTsInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeepLinkPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public DeepLinkType deepLinkType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint requestId
        {
            get { return __pbn__requestId.GetValueOrDefault(); }
            set { __pbn__requestId = value; }
        }
        public bool ShouldSerializerequestId() => __pbn__requestId != null;
        public void ResetrequestId() => __pbn__requestId = null;
        private uint? __pbn__requestId;

        [global::ProtoBuf.ProtoMember(3)]
        public uint padUniqueId
        {
            get { return __pbn__padUniqueId.GetValueOrDefault(); }
            set { __pbn__padUniqueId = value; }
        }
        public bool ShouldSerializepadUniqueId() => __pbn__padUniqueId != null;
        public void ResetpadUniqueId() => __pbn__padUniqueId = null;
        private uint? __pbn__padUniqueId;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string invitationId
        {
            get { return __pbn__invitationId ?? ""; }
            set { __pbn__invitationId = value; }
        }
        public bool ShouldSerializeinvitationId() => __pbn__invitationId != null;
        public void ResetinvitationId() => __pbn__invitationId = null;
        private string __pbn__invitationId;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sessionId
        {
            get { return __pbn__sessionId ?? ""; }
            set { __pbn__sessionId = value; }
        }
        public bool ShouldSerializesessionId() => __pbn__sessionId != null;
        public void ResetsessionId() => __pbn__sessionId = null;
        private string __pbn__sessionId;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string itemId
        {
            get { return __pbn__itemId ?? ""; }
            set { __pbn__itemId = value; }
        }
        public bool ShouldSerializeitemId() => __pbn__itemId != null;
        public void ResetitemId() => __pbn__itemId = null;
        private string __pbn__itemId;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string isSystemUiOverlaid
        {
            get { return __pbn__isSystemUiOverlaid ?? ""; }
            set { __pbn__isSystemUiOverlaid = value; }
        }
        public bool ShouldSerializeisSystemUiOverlaid() => __pbn__isSystemUiOverlaid != null;
        public void ResetisSystemUiOverlaid() => __pbn__isSystemUiOverlaid = null;
        private string __pbn__isSystemUiOverlaid;

        [global::ProtoBuf.ProtoMember(8, Name = @"result")]
        public uint Result
        {
            get { return __pbn__Result.GetValueOrDefault(); }
            set { __pbn__Result = value; }
        }
        public bool ShouldSerializeResult() => __pbn__Result != null;
        public void ResetResult() => __pbn__Result = null;
        private uint? __pbn__Result;

        [global::ProtoBuf.ProtoMember(9)]
        public bool shouldShow
        {
            get { return __pbn__shouldShow.GetValueOrDefault(); }
            set { __pbn__shouldShow = value; }
        }
        public bool ShouldSerializeshouldShow() => __pbn__shouldShow != null;
        public void ResetshouldShow() => __pbn__shouldShow = null;
        private bool? __pbn__shouldShow;

        [global::ProtoBuf.ProtoContract()]
        public enum DeepLinkType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SAVE_DATA")]
            SaveData = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"INVITE")]
            Invite = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GAME_ALERT")]
            GameAlert = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM_SERVICE_STATUS")]
            SystemServiceStatus = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"DEBUG_VSH_MENU")]
            DebugVshMenu = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DirectMessagePayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public DirectMessageType directMessageType { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Destination destination { get; set; } = Destination.GaikaiController;

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public byte[] Data
        {
            get { return __pbn__Data; }
            set { __pbn__Data = value; }
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

        [global::ProtoBuf.ProtoContract()]
        public enum DirectMessageType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEEPLINK")]
            Deeplink = 0,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Destination
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GAIKAI_CONTROLLER")]
            GaikaiController = 1000,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT")]
            Client = 1001,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SenkushaPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Command command { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public EchoCommand echoCommand { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public MtuCommand mtuCommand { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public BandwidthCommand bandwidthCommand { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ClientMtuCommand clientMtuCommand { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Command
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ECHO_COMMAND")]
            EchoCommand = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MTU_COMMAND")]
            MtuCommand = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BANDWIDTH_COMMAND")]
            BandwidthCommand = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MTU_COMMAND")]
            ClientMtuCommand = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EchoCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state", IsRequired = true)]
        public bool State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MtuCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint mtuReq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint mtuSent
        {
            get { return __pbn__mtuSent.GetValueOrDefault(); }
            set { __pbn__mtuSent = value; }
        }
        public bool ShouldSerializemtuSent() => __pbn__mtuSent != null;
        public void ResetmtuSent() => __pbn__mtuSent = null;
        private uint? __pbn__mtuSent;

        [global::ProtoBuf.ProtoMember(4, Name = @"num")]
        public uint Num
        {
            get { return __pbn__Num.GetValueOrDefault(); }
            set { __pbn__Num = value; }
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

        [global::ProtoBuf.ProtoMember(5)]
        public uint sendDelay
        {
            get { return __pbn__sendDelay.GetValueOrDefault(); }
            set { __pbn__sendDelay = value; }
        }
        public bool ShouldSerializesendDelay() => __pbn__sendDelay != null;
        public void ResetsendDelay() => __pbn__sendDelay = null;
        private uint? __pbn__sendDelay;

        [global::ProtoBuf.ProtoMember(6, Name = @"delta")]
        public uint Delta
        {
            get { return __pbn__Delta.GetValueOrDefault(); }
            set { __pbn__Delta = value; }
        }
        public bool ShouldSerializeDelta() => __pbn__Delta != null;
        public void ResetDelta() => __pbn__Delta = null;
        private uint? __pbn__Delta;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BandwidthCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"bandwidth")]
        public uint Bandwidth
        {
            get { return __pbn__Bandwidth.GetValueOrDefault(); }
            set { __pbn__Bandwidth = value; }
        }
        public bool ShouldSerializeBandwidth() => __pbn__Bandwidth != null;
        public void ResetBandwidth() => __pbn__Bandwidth = null;
        private uint? __pbn__Bandwidth;

        [global::ProtoBuf.ProtoMember(4, Name = @"fps")]
        public uint Fps
        {
            get { return __pbn__Fps.GetValueOrDefault(); }
            set { __pbn__Fps = value; }
        }
        public bool ShouldSerializeFps() => __pbn__Fps != null;
        public void ResetFps() => __pbn__Fps = null;
        private uint? __pbn__Fps;

        [global::ProtoBuf.ProtoMember(5, Name = @"mtu")]
        public uint Mtu
        {
            get { return __pbn__Mtu.GetValueOrDefault(); }
            set { __pbn__Mtu = value; }
        }
        public bool ShouldSerializeMtu() => __pbn__Mtu != null;
        public void ResetMtu() => __pbn__Mtu = null;
        private uint? __pbn__Mtu;

        [global::ProtoBuf.ProtoMember(6)]
        public uint naluCount
        {
            get { return __pbn__naluCount.GetValueOrDefault(); }
            set { __pbn__naluCount = value; }
        }
        public bool ShouldSerializenaluCount() => __pbn__naluCount != null;
        public void ResetnaluCount() => __pbn__naluCount = null;
        private uint? __pbn__naluCount;

        [global::ProtoBuf.ProtoMember(7)]
        public uint totalSent
        {
            get { return __pbn__totalSent.GetValueOrDefault(); }
            set { __pbn__totalSent = value; }
        }
        public bool ShouldSerializetotalSent() => __pbn__totalSent != null;
        public void ResettotalSent() => __pbn__totalSent = null;
        private uint? __pbn__totalSent;

        [global::ProtoBuf.ProtoMember(8, Name = @"upstream")]
        public bool Upstream
        {
            get { return __pbn__Upstream.GetValueOrDefault(); }
            set { __pbn__Upstream = value; }
        }
        public bool ShouldSerializeUpstream() => __pbn__Upstream != null;
        public void ResetUpstream() => __pbn__Upstream = null;
        private bool? __pbn__Upstream;

        [global::ProtoBuf.ProtoMember(9, Name = @"loss")]
        public double Loss
        {
            get { return __pbn__Loss.GetValueOrDefault(); }
            set { __pbn__Loss = value; }
        }
        public bool ShouldSerializeLoss() => __pbn__Loss != null;
        public void ResetLoss() => __pbn__Loss = null;
        private double? __pbn__Loss;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientMtuCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint mtuReq { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state", IsRequired = true)]
        public bool State { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint mtuDown
        {
            get { return __pbn__mtuDown.GetValueOrDefault(); }
            set { __pbn__mtuDown = value; }
        }
        public bool ShouldSerializemtuDown() => __pbn__mtuDown != null;
        public void ResetmtuDown() => __pbn__mtuDown = null;
        private uint? __pbn__mtuDown;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
